### PR TITLE
Set ContinuousIntegrationBuild = true only in Release configuration

### PR DESCRIPTION
**Pull request by 0xced**
This breaks debugging unit tests. Anyway, it's already set by the continuous integration workflow:
> env:
>   Configuration: Release
>   ContinuousIntegrationBuild: true

### CODE REVIEW

**Comment by 0xced** [comment]
> I've never had any issues debugging unit test. Can you be more specific? How do you run into problems?

I'm using Rider (on both macOS and Windows) and with the `ContinuousIntegrationBuild` MSBuild property set to `true`, Rider can't see breakpoints in the Core, PixelCanvas, and Windows projects so it becomes impossible to debug:

image

> The pack command fails since package validation fails

Indeed validation fails when the `ContinuousIntegrationBuild` property is not set and that's expected. You can make the validation pass by explicitly setting `ContinuousIntegrationBuild` to `true`:

```
dotnet pack --configuration Release -p:ContinuousIntegrationBuild=true
```

Note that for a _real_ continuous integration build, i.e. on GitHub actions, the `ContinuousIntegrationBuild` setting is set to `true` and the configuration is set to `Release` through environment variables ([all environment variables are available to the Microsoft Build Engine (MSBuild) project file as properties](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-environment-variables-in-a-build?view=vs-2022#reference-environment-variables)):

https://github.com/manuelbl/SwissQRBill.NET/blob/2acda640e4690657c940ed7b7aad360b5a2ad547/.github/workflows/continuous-integration.yml#L5-L7

**Comment by manuelbl** [comment]
Is there a way to make the *Pack* command within Visual Studio work again?

**Comment by 0xced** [comment]
I just did this in 78a87e5a02491f995de90dec07220609d784d4b9:

```xml
<ContinuousIntegrationBuild Condition="$(Configuration) == 'Release'">true</ContinuousIntegrationBuild>
```

This way, packing with the Release configuration works and debugging in Rider with the Debug configuration also works. 🥳

**Comment by 0xced** [comment]
Thanks for merging! 🚀 Are you planing to release a new version on NuGet soon?

**Comment by manuelbl** [comment]
I will likely release it within 2 days. The port to Java is already done.

**Pull request merged**
