### PR TITLE
Added PNG as a GraphicsFormat

### PR DESCRIPTION
**Pull request by nilsthomann**
PR for the issue #15

### CODE REVIEW

**Comment by manuelbl** [comment]
Thanks for the PR. I've merged it into *master* with some modifications.

**Comment by nilsthomann** [comment]
@manuelbl  Thank you very much. Have you planned to do a new release in the following days?

**Comment by manuelbl** [comment]
No specific plan yet. However, with the imminent start of QR bill, the heat is on and likely to be more changes and a release within a week.

**Comment by manuelbl** [comment]
It's now available as release 2.3.4.

**Pull request merged**
